# Generated by Django 2.1.4 on 2020-03-01 04:09

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('author', models.CharField(default='大海', max_length=30, verbose_name='作者')),
                ('content', tinymce.models.HTMLField(verbose_name='博客内容')),
                ('desc', models.CharField(default='', max_length=120, verbose_name='简介')),
                ('cat', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'db_table': 'blog_table',
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'cate_table',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=32, verbose_name='评论人IP')),
                ('content', models.CharField(max_length=120, verbose_name='评论内容')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blog', verbose_name='评论的博客')),
            ],
            options={
                'db_table': 'comment_table',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
            ],
            options={
                'db_table': 'tag_table',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='cate',
            field=models.ForeignKey(on_delete=True, to='blogapp.Cate', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blogapp.Tag', verbose_name='多对多标签'),
        ),
    ]
